# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SkeletonModel.py
# Created on: 2016-04-05 21:03:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Output_Feature_Class__2_ = ""
Input_Features = ""
Output_Features = Input_Features
Output_Table = ""
Output_Layer_Name = ""
Output_Layer_Name__2_ = ""
Layer_Name_or_Table_View = ""

# Process: Points To Line
arcpy.PointsToLine_management("", Output_Feature_Class__2_, "", "", "NO_CLOSE")

# Process: Add XY Coordinates
arcpy.AddXY_management(Input_Features)

# Process: Copy Rows
arcpy.CopyRows_management(Output_Features, Output_Table, "")

# Process: Add Join
arcpy.AddJoin_management("", "", "", "", "KEEP_ALL")

# Process: Add Join (2)
arcpy.AddJoin_management("", "", "", "", "KEEP_ALL")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management("", "", "", Layer_Name_or_Table_View, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")

